repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
    - id: go-fmt
    - id: go-vet
#    - id: go-imports  # todo enable later
#    - id: go-cyclo  # todo enable later
#      args: [-over=15]  # todo enable later
    - id: validate-toml
    - id: no-go-testing
#    - id: golangci-lint # todo enable later
#    - id: go-critic # todo enable later
#    - id: go-unit-tests  # todo enable later
    - id: go-build
    - id: go-mod-tidy
