BEGIN;

-- Currencies info
CREATE TABLE IF NOT EXISTS currencies(
    id              INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    currency_code	VARCHAR (10) UNIQUE

);
COMMENT ON TABLE currencies IS 'Table for currency info';

-- Monitoring table
CREATE TABLE IF NOT EXISTS monitorings(
    id           INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at   TIMESTAMP    NOT NULL DEFAULT NOW(),

    started_at   TIMESTAMP    NOT NULL DEFAULT NOW(),
    expired_at   TIMESTAMP    NOT NULL DEFAULT NOW() + interval '1 hour',

    frequency    TEXT         NOT NULL, -- precision (or delta in time) between two requests -- 1s, 10s, 1m

    currency_id  INTEGER      NOT NULL,

    CONSTRAINT fkey__currencies_id FOREIGN KEY (currency_id)
        REFERENCES currencies(id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION
);
COMMENT ON TABLE monitorings IS 'Table for monitoring information';

-- BTCUSD prices
CREATE TABLE btcusd_prices (
    time     TIMESTAMP NOT NULL,
    price    DOUBLE PRECISION
);
COMMENT ON TABLE btcusd_prices IS 'Table for btcusdt prices';

-- TODO FOR LATER other tables can use this approach
-- -- CREATE TABLE ethusd_prices (LIKE btcusdt_prices INCLUDING ALL);


--Timescale specific statements to create hypertables for better performance
SELECT create_hypertable('btcusd_prices', 'time', 'price', 2);


-- fixture
INSERT INTO currencies(id, currency_code) VALUES(1, 'BTCUSD');

COMMIT;
