BEGIN;

-- Currency info
CREATE TABLE IF NOT EXISTS currency_info(
    currency_code	VARCHAR (10) UNIQUE,
    currency 		TEXT

);
COMMENT ON TABLE currency_info IS 'Table for currency info';

-- Monitoring table
CREATE TABLE IF NOT EXISTS monitoring(
    id           INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at   TIMESTAMP    NOT NULL DEFAULT NOW(),
    expired_at   TIMESTAMP    NOT NULL DEFAULT NOW() + interval '1 hour',

    frequency    TIME         NOT NULL, -- precision (or delta in time) between two requests

    currency_code VARCHAR (10)
);
COMMENT ON TABLE monitoring IS 'Table for monitoring information';

-- BTC prices
CREATE TABLE btc_prices (
    time            TIMESTAMP WITH TIME ZONE NOT NULL,
    price           DOUBLE PRECISION
);
COMMENT ON TABLE btc_prices IS 'Table for btc prices';


--Timescale specific statements to create hypertables for better performance
SELECT create_hypertable('btc_prices', 'time', 'price', 2);

COMMIT;
