logger:
  level: info
  encoding: console
  color: true
  outputs:
    - stdout
  tags:

consul:
  address: 127.0.0.1:8500
  interval: 2s
  timeout: 250ms
  tags:
    - pm
  dns:
    - "8.8.8.8:80"
  sessionTTL: 30s

servers:
  http:
    name: pm-http-api
    address: :8080
    domainName: localhost
    allowOrigin: "*"
    timeouts:
      readTimeout: "30s"
      writeTimeout: "30s"

services:
  storage:
    host: "127.0.0.1"
    port: 5432
    database: pm
    maxTryConnect: 3
    timeoutTryConnect: "5s"
    options:
      maxLifeTime: 600
      maxIdleConn: 10
      maxOpenConn: 10

  controllers:
    general:
      monitor:
        timeoutConsulLeaderCheck: "1s" # TODO define that we can lose 1 second (need discuss!)

    master:
      scanner:
        timeoutOneTaskProcess: "2s" # TODO define max timeout for one task (need discuss!)
        intervalPeriodicScan: "1s" # TODO define max frequency for price scanner (need discuss!)
        cntWorkers: 1
